name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-smart-docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create test Dockerfile
      run: |
        echo "FROM alpine:3.18" > Dockerfile
        echo "RUN echo 'Hello from test container'" >> Dockerfile

    - name: Test smart-docker-build action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        use_dryrun: 'true'