name: Integration Tests

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test-smart-docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test smart-docker-build action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        use_dryrun: 'true'
