name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/get/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'internal/get/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./internal/get

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './internal/get/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
